version: '3.7'

services:
  app:
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      target: build-env
    env_file:
      - docker/app/.env.dist
    volumes:
      - type: bind
        source: .
        target: /nook
    working_dir: /nook
    ports:
      - 8080:8080
    depends_on:
      - db
    command: bash -c "./scripts/dev.sh"

  db:
    build: ./docker/mariadb/
    environment:
      MYSQL_ROOT_PASSWORD: nook_root_pass
      MYSQL_DATABASE: nook_db
      MYSQL_USER: nook_user
      MYSQL_PASSWORD: nook_pass
    ports:
      - 3306:3306
    restart: always